# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildandDeploy:

    runs-on: windows-latest
    
    steps:
      - name: Running Sample .Net Application
      - uses: actions/checkout@main
        run: |
          echo $pwd > test.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
           name: application
           path: test.txt
      
      - name: Move the Artifact
        run: |
          ./test.ps1
              
                 
          
            

           

          
